import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
    linearBackground:{
        alignItems:'center',
        flex:1,
        flexDirection:'column',
        padding:10,
        paddingBottom:30,
    },
    screenBackground:{
        height:'100%',
        width:'100%',
    },
    screenItem:{
        alignSelf:'center',
        margin:20,
    },
    screenName:{
        color:'white',
        fontWeight:'bold',
        fontSize:30,
        textAlign:'center',
    },
    screenBottom:{
        fontSize:15,
        color:'white',
        textAlign:'center',
    },
    screenTitle:{
        color:'white',
        fontWeight:'bold',
        fontSize:50,
        textAlign:'center',
        marginBottom:30,
    },
    screenSafeView:{
        flex:1,
        flexDirection:'column',
        justifyContent:'space-between',
    },
    screenContainer:{
        flex:1,
        alignContent:'center',
        flexDirection:'column',
        justifyContent:'flex-start',
        width:'100%',
    }
})